version: '2.2'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: elasticsearch
    hostname: "{{.Node.Hostname}}-elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
      #- './scripts/setup-users.sh:/usr/local/bin/setup-users.sh:ro'
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"


  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    container_name: kibana
    hostname: "{{.Node.Hostname}}-kibana"
    ports:
      - 80:5601
    networks:
      - esnet
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME:
      ELASTICSEARCH_PASSWORD:
      STATUS_ALLOW_ANONYMOUS:
      XPACK_MONITORING_ENABLED:
      XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED:
      XPACK_REPORTING_ENABLED:
      XPACK_SECURITY_ENABLED:



  logstash:
    image: docker.elastic.co/logstash/logstash:6.5.4
    container_name: logstash
    hostname: "{{.Node.Hostname}}-logstash"
    ports:
      - 5044:5044
      - 9600:9600
    networks:
      - esnet
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/data:/usr/share/logstash/data
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200


volumes:
  esdata:
    driver: local
  filebeat:


networks:
  esnet:
    driver: bridge
    external: true
    ipam:
      driver: default
      config:
        - subnet: 127.0.0.0/24
